version: "3"

services:
  frontend:
    container_name: frontend
    build: .
    environment:
      env_file: .env
      NODE_ENV: development
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
