matrix:
  include:
    # - stage: Integration tests
    #   language: ruby
    #   services:
    #     - docker
    #   before_install:
    #     - sudo /etc/init.d/postgresql stop
    #   install:
    #     - touch backend/local_settings.py
    #     - docker-compose build
    #     - docker-compose run web python manage.py migrate --noinput && docker-compose run web python manage.py loaddata database.json
    #     - cd frontend && npm install && npm run build
    #   script:
    #     - cd .. && docker-compose up -d
    #     - cd frontend
    #     - ./node_modules/.bin/cypress install
    #     - wait-on http://localhost:8000 && ./node_modules/.bin/cypress run
    - stage: Backend tests
      language: python
      python:
        - "3.6"
      install:
        - pip install -r requirements.txt
      services:
        - postgresql
      addons:
        postgresql: "9.6"
      before_script:
        - psql -c 'create database travis_ci_test;' -U postgres
        - python manage.py migrate
      script: coverage run manage.py test
    - stage: Frontend tests
      language: node_js
      node_js:
        - "12.4"
      install:
        - cd frontend && npm install
      cache:
        directories:
          - frontend/node_modules
      script:
        - npm run lint
        - npm test
    - stage: Deploy to production
      script: skip
      deploy: &heroku
        provider: heroku
        api_key:
          secure: ZOMCSn76ZPy8K9ILreJ3MQKGsjJUQyUJVcfsj4HFFiVWG5lD24pxZG4++o0HJQCuUJ5wamzbe8OXithjAjDR1cdUNA0NQzVuv2E20vsmbT+12Y4JMdy/Bxm5l+d3ASxThE7Vb/sVRkTAFEJ9bxv70iIOSkwzrlCKZsawCGZkgVEDB7REEtOINgYz4Ek3V2pDcPBOvf9u/pWdlAoI9PT2RXPxUZqbCBz6zYDxWHLRKuC88UMZvKzjpld01GpsqEQ2CpcMckXa5u6UK3MTSvFSobqN71NGkQGm1O/fpBMeI3vLsKr/227UppbE362tSi8GWwHh8BRaQ53I976DjIBzwJSm9RZzAF4dC7ZnG9jyE8EZYWVJdzQe/6G9vSQNY+/cJrAjdksn7/8YU5T8s38C1rtv8NjDshLE5/ijqBN2W23Ez1LmUnCB6dtqj6XCEYdODGEKAWQJWMn9dDRFEIo5qpUA1ScLVahS9Ww6L79hrFHbStTIdpOqJMHTjqTO1NFXzNm6xPPAZjbZgripGg7PmqxWuqRlUXP07rCdihkyRj9xAacVwPiALbsW14foZxqvUMpUNFH5vFKe6yOr8RMN5cV+8tpkP4pmdXzY1TQdGR4ZBJeSz2vvcL2oaDsc5f7yqaPtxvYcCm3mk+p22nPhS19Nea/SNVk1lYoiy3b5fZo=
        app: w4nderlist
    - stage: Test deployment
      script: "curl http://w4nderlist.herokuapp.com"
