matrix:
  include:
    # - stage: Integration tests
    #   language: ruby
    #   services:
    #     - docker
    #   before_install:
    #     - sudo /etc/init.d/postgresql stop
    #   install:
    #     - touch backend/local_settings.py
    #     - docker-compose build
    #     - docker-compose run web python manage.py migrate --noinput && docker-compose run web python manage.py loaddata database.json
    #     - cd frontend && npm install && npm run build
    #   script:
    #     - cd .. && docker-compose up -d
    #     - cd frontend
    #     - ./node_modules/.bin/cypress install
    #     - wait-on http://localhost:8000 && ./node_modules/.bin/cypress run
    - stage: Backend tests
      language: python
      python:
        - "3.6"
      install:
        - pip install -r requirements.txt
      services:
        - postgresql
      addons:
        postgresql: "9.6"
      before_script:
        - psql -c 'create database travis_ci_test;' -U postgres
        - python manage.py migrate
      script: coverage run manage.py test
    - stage: Frontend tests
      language: node_js
      node_js:
        - "12.4"
      install:
        - cd frontend && npm install
      cache:
        directories:
          - frontend/node_modules
      script:
        - npm run lint
        - npm test
    - stage: Deploy to production
      script: skip
      deploy: &heroku
        provider: heroku
        api_key:
          secure: y2Iy8Oz0vycyRCUdcpuCP68vZVfpt78ezOSAk7zMoZCyisWypZvruy7FBH4Mnjm2idEjOZOy44MLJ/1qTQJF/L/Esn8c305Yzc7QG5L8yjx6JwCmkqqEHitP6jWXBXIILTultz7yMORcp51GSRavtYyk9n6fwXD4UsGQp2/nmdNekwZpmcQfE/NUl4W2r6uQ2l4N/d32GTXTnGoBzmnxvgU8cDp/faGzUB9zgM4QMncEV6o8rmW/NaN7olIDKI4pcHDpjODhbe9IKP8R/aJJzNTyf+HvlzIRB5KrYV2wSLtdOjpZMgdgHmB4+bVgY0z44vCPKupHMiVQxbx8Zac6aHdkO+UTxGK6M+wxXzgsTsmOSAv893jtefxWkEcjHi10lbjbs+6zo2IhK3MuoaMsWo/IuUf3+hockXmpYSsbBVV21/UaC7xMOwom5PXeUF0YhL5Quw+j10YESoPjFxGP4Mou97fwSwWTi6BlZmhz+X8ls4lcdbFzq2s7Etw0lJSjfh/bGLrnR2Rhu9bID77cFSAxCy4I95TpELq+qJGdOz7/uC8dKkQNXKkPWYwE5Cqcn/6isItXxJtOhcB4SDpTR4FwTULg2Ph1wZbYlMVt75V3JDIbs2oRtFIvUmNhVVBAHxKZWdCStHajcvtFsydI+F813wqOBFaTuDnp3HkcLu8=
        app: w4nderlist
    - stage: Test deployment
      script: "curl http://w4nderlist.herokuapp.com"
