language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
services:
  - postgresql
addons:
  postgresql: "10.5"
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - python manage.py migrate
script:
  coverage run manage.py test
